import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.security.MessageDigest

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.hilt)
    alias(libs.plugins.ksp)
}

// ── Consent hash generation ────────────────────────────────────────────────

/**
 * Reads every consent asset, computes its SHA-256, and writes ConsentHashes.kt.
 * Declared as an abstract task class so Gradle can serialize it for the
 * configuration cache (script closures capturing project refs cannot be cached).
 */
abstract class GenerateConsentHashesTask : DefaultTask() {

    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val consentAssetsDir: DirectoryProperty

    @get:OutputDirectory
    abstract val generatedHashesDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val assetsDir = consentAssetsDir.get().asFile
        val outputRoot = generatedHashesDir.get().asFile

        val hashes = sortedMapOf<String, String>()
        assetsDir
            .listFiles { f -> f.extension == "txt" }
            ?.sorted()
            ?.forEach { file ->
                val digest = MessageDigest.getInstance("SHA-256")
                val hashBytes = digest.digest(file.readBytes())
                hashes[file.nameWithoutExtension] = hashBytes.joinToString("") { "%02x".format(it) }
            }

        val outputFile = File(outputRoot, "app/invigilator/core/consent/ConsentHashes.kt")
        outputFile.parentFile.mkdirs()
        outputFile.writeText(buildString {
            appendLine("package app.invigilator.core.consent")
            appendLine()
            appendLine("// DO NOT EDIT — generated by the verifyConsentHashes Gradle task.")
            appendLine("// Re-run: ./gradlew :core:verifyConsentHashes")
            appendLine("internal object ConsentHashes {")
            appendLine("    /** SHA-256 of each consent asset as of the last build. */")
            appendLine("    val EXPECTED: Map<String, String> = mapOf(")
            hashes.forEach { (key, hash) -> appendLine("        \"$key\" to \"$hash\",") }
            appendLine("    )")
            appendLine("}")
        })
    }
}

val verifyConsentHashes by tasks.registering(GenerateConsentHashesTask::class) {
    group = "verification"
    description = "Generates ConsentHashes.kt from the SHA-256 of every consent asset."
    consentAssetsDir.set(layout.projectDirectory.dir("src/main/assets/consents"))
    generatedHashesDir.set(layout.buildDirectory.dir("generated/consent_hashes"))
}

android {
    namespace = "app.invigilator.core"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    sourceSets {
        getByName("main").kotlin.srcDir(
            verifyConsentHashes.flatMap { it.generatedHashesDir }
        )
    }
}

// Wire hash generation before KSP and Kotlin compile tasks
tasks.matching { it.name.startsWith("ksp") }.configureEach {
    dependsOn(verifyConsentHashes)
}
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    dependsOn(verifyConsentHashes)
}

dependencies {
    // ── AndroidX ──────────────────────────────────────────────────────────────
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)

    // ── Serialization ─────────────────────────────────────────────────────────
    implementation(libs.kotlinx.serialization.json)

    // ── Hilt ──────────────────────────────────────────────────────────────────
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)

    // ── Coroutines ────────────────────────────────────────────────────────────
    implementation(libs.kotlinx.coroutines.android)

    // ── Firebase ──────────────────────────────────────────────────────────────
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.auth)
    implementation(libs.firebase.firestore)
    implementation(libs.firebase.functions)

    // ── Logging ───────────────────────────────────────────────────────────────
    implementation(libs.timber)

    // ── Testing ───────────────────────────────────────────────────────────────
    testImplementation(libs.junit)
    testImplementation(libs.mockk)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.turbine)
}
