/**
 * Expected SHA-256 hashes of consent asset files.
 *
 * Generated by running: scripts/sync-consent-hashes.sh
 *
 * These are the hashes of the exact bytes in
 * core/src/main/assets/consents/*.txt at time of last sync.
 * The onConsentCreate trigger rejects any consent record whose
 * consentTextHash does not match the value here for that type+version.
 *
 * To update: bump the version in ConsentVersions.kt, edit the asset,
 * run `scripts/sync-consent-hashes.sh`, then redeploy functions.
 */
export const CONSENT_VERSION_HASHES: Record<string, Record<string, Record<string, string>>> = {
  AdultStudentSelfConsent: {
    "v1.0": {
      en: "6b4f2768bca68a5904aa7620e9460895396638991328bace222ed68e22cc65e4",
      as: "e1f8975ca8524957eae0d91d83a5ab02aa2066a692241765601fbf5207b61e2e",
      hi: "af27be3490d934ea1cccbae575c1e3a1e71daf5b3f81a4883df06494c88c8a6a",
      bn: "994a014770ca41f44f6e801abc8b88d15908a2adba765890227459cc7be18dea",
    },
  },
  ParentForMinorConsent: {
    "v1.0": {
      en: "b3226c7dfd68246d67ffe2afa420336d45e052167f43e4f44957e3a4169df941",
      as: "8c630310dd89629d18251de0a5e88ce43b157013ae27a497a46af06bc392befa",
      hi: "7f48eade2d352ecd4c895893bb6d364a328518ef4d15f37786a38222ec691c63",
      bn: "38e5be15a5b04bba093e437e6a29174b161afcda97dc66534f667c5a41a1009a",
    },
  },
  ParentTermsOfService: {
    "v1.0": {
      en: "4ddf6b9875d9d5a00b96bca59676a0bb3f4ecf23bef7b8b719c5325fbc536a33",
      as: "ba10b1ceda14c4c8f08e01db975ba04d7fae2e888e723df4a6178e345e441f69",
      hi: "2e921cee3e3e8b141cfd61e55b614ea67eea49658d9e0a320c325889ea3db7fa",
      bn: "f7e560f2412f6784765380ff1583a388730426aa06d238c6a988fa5f63a68fbf",
    },
  },
};
