#!/usr/bin/env bash
# sync-consent-hashes.sh
#
# Computes SHA-256 of every consent asset and rewrites
# backend/functions/src/consentHashes.ts with the new values.
#
# Run this after editing any consent text or bumping a version, then redeploy functions.
# The Android build's verifyConsentHashes task handles the Kotlin side automatically.
#
# Usage: scripts/sync-consent-hashes.sh

set -euo pipefail

ASSETS_DIR="$(git rev-parse --show-toplevel)/core/src/main/assets/consents"
OUT_FILE="$(git rev-parse --show-toplevel)/backend/functions/src/consentHashes.ts"

if [[ ! -d "$ASSETS_DIR" ]]; then
  echo "ERROR: assets dir not found: $ASSETS_DIR" >&2
  exit 1
fi

# Build a map: type -> version -> language -> hash
declare -A HASHES

for f in "$ASSETS_DIR"/*.txt; do
  filename="$(basename "$f" .txt)"   # e.g. AdultStudentSelfConsent_v1.0_en
  # Split on underscore groups: TYPE_VERSION_LANG
  # TYPE can contain underscores, so split from the right
  lang="${filename##*_}"                          # en
  rest="${filename%_*}"                           # AdultStudentSelfConsent_v1.0
  version="${rest##*_}"                           # v1.0
  type="${rest%_*}"                               # AdultStudentSelfConsent
  hash="$(shasum -a 256 "$f" | awk '{print $1}')"
  HASHES["${type}::${version}::${lang}"]="$hash"
done

# Group into type -> version -> language structure
declare -A TYPES
for key in "${!HASHES[@]}"; do
  IFS='::' read -ra parts <<< "$key"
  type="${parts[0]}"
  TYPES["$type"]=1
done

cat > "$OUT_FILE" <<'HEADER'
/**
 * Expected SHA-256 hashes of consent asset files.
 *
 * Generated by running: scripts/sync-consent-hashes.sh
 *
 * These are the hashes of the exact bytes in
 * core/src/main/assets/consents/*.txt at time of last sync.
 * The onConsentCreate trigger rejects any consent record whose
 * consentTextHash does not match the value here for that type+version.
 *
 * To update: bump the version in ConsentVersions.kt, edit the asset,
 * run `scripts/sync-consent-hashes.sh`, then redeploy functions.
 */
export const CONSENT_VERSION_HASHES: Record<string, Record<string, Record<string, string>>> = {
HEADER

for type in $(echo "${!TYPES[@]}" | tr ' ' '\n' | sort); do
  echo "  $type: {" >> "$OUT_FILE"

  # Collect versions for this type
  declare -A VERSIONS
  for key in "${!HASHES[@]}"; do
    IFS='::' read -ra parts <<< "$key"
    if [[ "${parts[0]}" == "$type" ]]; then
      VERSIONS["${parts[1]}"]=1
    fi
  done

  for version in $(echo "${!VERSIONS[@]}" | tr ' ' '\n' | sort); do
    echo "    \"$version\": {" >> "$OUT_FILE"
    for lang in en as hi bn; do
      hash="${HASHES["${type}::${version}::${lang}"]:-}"
      if [[ -n "$hash" ]]; then
        echo "      $lang: \"$hash\"," >> "$OUT_FILE"
      fi
    done
    echo "    }," >> "$OUT_FILE"
  done
  unset VERSIONS

  echo "  }," >> "$OUT_FILE"
done

echo "};" >> "$OUT_FILE"

echo "✓ consentHashes.ts updated at $OUT_FILE"
