#!/usr/bin/env bash
# sync-consent-hashes.sh
#
# Computes SHA-256 of every consent asset and rewrites
# backend/functions/src/consentHashes.ts with the new values.
#
# Run this after editing any consent text or bumping a version, then redeploy functions.
# The Android build's verifyConsentHashes task handles the Kotlin side automatically.
#
# Usage:
#   scripts/sync-consent-hashes.sh           # compute + write consentHashes.ts
#   scripts/sync-consent-hashes.sh --check   # compute only; exit 1 if out of sync (CI mode)

set -euo pipefail

CHECK_MODE=0
for arg in "$@"; do
  if [[ "$arg" == "--check" ]]; then
    CHECK_MODE=1
  fi
done

ROOT="$(git rev-parse --show-toplevel)"
ASSETS_DIR="$ROOT/core/src/main/assets/consents"
OUT_FILE="$ROOT/backend/functions/src/consentHashes.ts"

if [[ ! -d "$ASSETS_DIR" ]]; then
  echo "ERROR: assets dir not found: $ASSETS_DIR" >&2
  exit 1
fi

if [[ "$CHECK_MODE" == "1" && ! -f "$OUT_FILE" ]]; then
  echo "ERROR: $OUT_FILE does not exist; cannot check for drift." >&2
  exit 1
fi

# Delegate hash computation and TS generation to Python 3 (portable across
# macOS bash 3.2 and Linux bash 5+; avoids declare -A requirement).
TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT

python3 - "$ASSETS_DIR" "$TMPFILE" <<'PYEOF'
import sys, hashlib, os, collections

assets_dir, out_path = sys.argv[1], sys.argv[2]

# Parse filenames: AdultStudentSelfConsent_v1.0_en.txt
# lang  = last segment after final _
# ver   = second-to-last segment
# type  = everything before the last two _-separated segments
hashes = {}  # (type, version, lang) -> sha256

for fname in os.listdir(assets_dir):
    if not fname.endswith(".txt"):
        continue
    stem = fname[:-4]
    parts = stem.rsplit("_", 2)
    if len(parts) != 3:
        print(f"WARNING: skipping unrecognised filename: {fname}", file=sys.stderr)
        continue
    consent_type, version, lang = parts[0], parts[1], parts[2]
    filepath = os.path.join(assets_dir, fname)
    with open(filepath, "rb") as f:
        digest = hashlib.sha256(f.read()).hexdigest()
    hashes[(consent_type, version, lang)] = digest

# Group
tree = collections.defaultdict(lambda: collections.defaultdict(dict))
for (t, v, l), h in hashes.items():
    tree[t][v][l] = h

lines = []
lines.append("/**")
lines.append(" * Expected SHA-256 hashes of consent asset files.")
lines.append(" *")
lines.append(" * Generated by running: scripts/sync-consent-hashes.sh")
lines.append(" *")
lines.append(" * These are the hashes of the exact bytes in")
lines.append(" * core/src/main/assets/consents/*.txt at time of last sync.")
lines.append(" * The onConsentCreate trigger rejects any consent record whose")
lines.append(" * consentTextHash does not match the value here for that type+version.")
lines.append(" *")
lines.append(" * To update: bump the version in ConsentVersions.kt, edit the asset,")
lines.append(" * run `scripts/sync-consent-hashes.sh`, then redeploy functions.")
lines.append(" */")
lines.append("export const CONSENT_VERSION_HASHES: Record<string, Record<string, Record<string, string>>> = {")

for t in sorted(tree):
    lines.append(f"  {t}: {{")
    for v in sorted(tree[t]):
        lines.append(f'    "{v}": {{')
        for lang in ["en", "as", "hi", "bn"]:
            if lang in tree[t][v]:
                lines.append(f'      {lang}: "{tree[t][v][lang]}",')
        lines.append("    },")
    lines.append("  },")

lines.append("};")
lines.append("")

with open(out_path, "w") as f:
    f.write("\n".join(lines))
PYEOF

# ── Check mode: diff generated content against committed file ─────────────────
if [[ "$CHECK_MODE" == "1" ]]; then
  if diff -q "$TMPFILE" "$OUT_FILE" > /dev/null 2>&1; then
    echo "✓ consent hashes are in sync (no drift)"
    exit 0
  else
    echo "✗ consent hash drift detected!" >&2
    echo "  consentHashes.ts does not match the current asset files." >&2
    echo "  Run: scripts/sync-consent-hashes.sh  then redeploy functions." >&2
    echo "" >&2
    diff "$OUT_FILE" "$TMPFILE" >&2 || true
    exit 1
  fi
fi

# ── Write mode: replace the committed file ────────────────────────────────────
cp "$TMPFILE" "$OUT_FILE"
echo "✓ consentHashes.ts updated at $OUT_FILE"
